disable_heatmaps:
  type: bool
  default: false
  description: "Disable funscript heatmap generation entirely"

solid_background:
  type: bool
  default: false
  description: "Use solid background color instead of gradient in heatmaps"

cache_heatmaps:
  type: bool
  default: true
  description: "Cache heatmaps for faster loading"
